import React from 'react';


function Content() {
    return (
        <main className="content">
            <section id="content1" className="content1">
            <h1>first Content Area</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            </section>
            <section id="content2" className="content2">
            <h1>Second Content Area</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            </section>
            <section id="content13" className="content3">
            <h1>Third Content Area</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            </section>
            <section id="content4" className="content4">
            <h1>Fourth Content Area</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis sunt aut velit doloribus cumque, ea aperiam reiciendis minus. Ipsum odio, adipisci reiciendis totam aperiam neque voluptate minus cum a minima! Tenetur, excepturi voluptatum et sapiente adipisci consequatur assumenda minus, perspiciatis hic suscipit accusantium molestias pariatur corporis id. Asperiores explicabo fugiat voluptates illo hic qui, exercitationem iste dignissimos facilis sint libero reiciendis sapiente ex maxime, vel soluta quod minus. Minus ullam quasi debitis sint voluptates praesentium voluptatum maxime. Ex incidunt quo libero suscipit quis quidem quisquam debitis cumque, laudantium sapiente odio dolores voluptates corrupti quos voluptate harum assumenda voluptas blanditiis architecto!</p>
            </section>
        </main>
    );
  }
  

export default Content;